/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlycongdan;

import com.sun.istack.internal.logging.Logger;
import java.awt.Color;
import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.NotSerializableException;
import java.io.ObjectInputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author Hades
 */
public class QuanLyCongDan extends javax.swing.JFrame {

    List<CongDan> list = new ArrayList<>();
    public void add() {
        CongDan cd = new CongDan();
        cd.CMND = txtSoCMND.getText();
        cd.ten = txtTen.getText();
        cd.gioiTinh = cboGioiTinh.getSelectedItem().toString();
        cd.namSinh = cboNamSinh.getSelectedItem().toString();
        cd.queQuan = txtQueQuan.getText();
        cd.ngheNghiep = cboNghe.getSelectedItem().toString();
        cd.choOHienNay = txtChoOHienNay.getText();
        cd.hinhAnh=(ImageIcon) lblAnh.getIcon();

        list.add(cd);
    }

    public void delete() {
        int index = tblBang.getSelectedRow();
        list.remove(index);
    }

    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblBang.getModel();
        model.setRowCount(0);
        for (CongDan cd : list) {
            Object[] row = new Object[]{
                cd.CMND,
                cd.ten,
                cd.gioiTinh,
                cd.namSinh,
                cd.queQuan,
                cd.ngheNghiep,
                cd.choOHienNay,
                cd.hinhAnh
            };
            model.addRow(row);
        }
    }

    /**
     * Creates new form QuanLySinhVien
     */
    public QuanLyCongDan() {
        initComponents();
        dongho();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblNamSinh = new javax.swing.JLabel();
        lblSoCMND = new javax.swing.JLabel();
        lblQueQuan = new javax.swing.JLabel();
        lblChoOHienNay = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtSoCMND = new javax.swing.JTextField();
        txtQueQuan = new javax.swing.JTextField();
        txtChoOHienNay = new javax.swing.JTextField();
        btnMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnMo = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        cboGioiTinh = new javax.swing.JComboBox<>();
        lblGioiTinh = new javax.swing.JLabel();
        btnTrangTruoc = new javax.swing.JButton();
        btnTenTruoc = new javax.swing.JButton();
        btnTenSau = new javax.swing.JButton();
        btnTrangSau = new javax.swing.JButton();
        lblNghe = new javax.swing.JLabel();
        cboNghe = new javax.swing.JComboBox<>();
        lblAnh = new javax.swing.JLabel();
        cboNamSinh = new javax.swing.JComboBox<>();
        lblClock = new javax.swing.JLabel();
        lblRecord = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnThemAnh = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý công dân");
        setLocation(new java.awt.Point(0, 0));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("UTM Charlemagne", 1, 19)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 255));
        lblTitle.setText("QUẢN LÝ CÔNG DÂN");

        lblTen.setFont(new java.awt.Font("UTM BryantLG", 1, 18)); // NOI18N
        lblTen.setText("Họ tên công dân:");

        lblNamSinh.setFont(new java.awt.Font("UTM BryantLG", 1, 18)); // NOI18N
        lblNamSinh.setText("Năm sinh:");

        lblSoCMND.setFont(new java.awt.Font("UTM BryantLG", 1, 18)); // NOI18N
        lblSoCMND.setText("Số CMND:");

        lblQueQuan.setFont(new java.awt.Font("UTM BryantLG", 1, 18)); // NOI18N
        lblQueQuan.setText("Quê quán:");

        lblChoOHienNay.setFont(new java.awt.Font("UTM BryantLG", 1, 18)); // NOI18N
        lblChoOHienNay.setText("Chỗ ở hiện nay:");

        txtTen.setFont(new java.awt.Font("UTM BryantLG", 1, 16)); // NOI18N
        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });

        txtSoCMND.setFont(new java.awt.Font("UTM BryantLG", 1, 16)); // NOI18N

        txtQueQuan.setFont(new java.awt.Font("UTM BryantLG", 1, 16)); // NOI18N

        txtChoOHienNay.setFont(new java.awt.Font("UTM BryantLG", 1, 16)); // NOI18N

        btnMoi.setFont(new java.awt.Font("UTM BryantLG", 1, 16)); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("UTM BryantLG", 1, 16)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("UTM BryantLG", 1, 16)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("UTM BryantLG", 1, 16)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnMo.setFont(new java.awt.Font("UTM BryantLG", 1, 16)); // NOI18N
        btnMo.setText("Mở");
        btnMo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("UTM BryantLG", 1, 16)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 0, 0));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        tblBang.setFont(new java.awt.Font("UTM BryantLG", 1, 18)); // NOI18N
        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Số CMND", "Họ và tên", "Giới tính", "Năm sinh", "Quê quán", "Nghề nghiệp", "Chỗ ở hiện nay"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBang.setFocusable(false);
        tblBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangOnMouseClick(evt);
            }
        });
        jScrollPane3.setViewportView(tblBang);

        cboGioiTinh.setFont(new java.awt.Font("UTM BryantLG", 1, 18)); // NOI18N
        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Nam", "Nữ" }));

        lblGioiTinh.setFont(new java.awt.Font("UTM BryantLG", 1, 18)); // NOI18N
        lblGioiTinh.setText("Giới tính:");

        btnTrangTruoc.setText("|<");
        btnTrangTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangTruocActionPerformed(evt);
            }
        });

        btnTenTruoc.setText("<<");
        btnTenTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTenTruocActionPerformed(evt);
            }
        });

        btnTenSau.setText(">>");
        btnTenSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTenSauActionPerformed(evt);
            }
        });

        btnTrangSau.setText(">|");
        btnTrangSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangSauActionPerformed(evt);
            }
        });

        lblNghe.setFont(new java.awt.Font("UTM BryantLG", 1, 18)); // NOI18N
        lblNghe.setText("Nghề nghiệp");

        cboNghe.setFont(new java.awt.Font("UTM BryantLG", 1, 18)); // NOI18N
        cboNghe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "Nông dân", "Công chức", "Văn phòng", "Học sinh", "Thất Nghiệp" }));
        cboNghe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNgheActionPerformed(evt);
            }
        });

        lblAnh.setBackground(new java.awt.Color(60, 63, 75));
        lblAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/default.png"))); // NOI18N
        lblAnh.setText("anh");
        lblAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Picture(evt);
            }
        });

        cboNamSinh.setFont(new java.awt.Font("UTM BryantLG", 1, 18)); // NOI18N
        cboNamSinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", " " }));
        cboNamSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNamSinhActionPerformed(evt);
            }
        });

        lblClock.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblClock.setForeground(new java.awt.Color(255, 0, 0));

        lblRecord.setForeground(new java.awt.Color(255, 0, 0));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        btnThemAnh.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        btnThemAnh.setText("Thêm ảnh");
        btnThemAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemAnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGioiTinh)
                    .addComponent(lblSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChoOHienNay))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtChoOHienNay, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblNghe)
                .addGap(76, 76, 76)
                .addComponent(cboNghe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(btnThemAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(btnTrangTruoc)
                .addGap(18, 18, 18)
                .addComponent(btnTenTruoc)
                .addGap(18, 18, 18)
                .addComponent(btnTenSau)
                .addGap(18, 18, 18)
                .addComponent(btnTrangSau)
                .addGap(46, 46, 46)
                .addComponent(lblRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblTen))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(23, 23, 23)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblNamSinh)
                        .addGap(21, 21, 21)
                        .addComponent(lblGioiTinh)
                        .addGap(17, 17, 17)
                        .addComponent(lblSoCMND)
                        .addGap(11, 11, 11)
                        .addComponent(lblQueQuan)
                        .addGap(18, 18, 18)
                        .addComponent(lblChoOHienNay))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(cboNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txtSoCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtChoOHienNay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblAnh))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMoi)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuu)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnMo)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblNghe))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cboNghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnThemAnh)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnThoat)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTrangTruoc)
                    .addComponent(btnTenTruoc)
                    .addComponent(btnTenSau)
                    .addComponent(btnTrangSau)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        int i = 0;


    public void showDetail() {
        int index = tblBang.getSelectedRow();
        CongDan cd = list.get(index);
        String rec=String.valueOf(index+1);
        lblRecord.setText("Record: "+rec+"of"+list.size());
        lblAnh.setIcon(cd.hinhAnh);
        txtTen.setText(cd.ten);
        cboNamSinh.setSelectedItem(cd.namSinh);
        cboGioiTinh.setSelectedItem(cd.gioiTinh);
        txtSoCMND.setText(cd.CMND);
        txtQueQuan.setText(cd.queQuan);
        txtChoOHienNay.setText(cd.choOHienNay);
        cboNghe.setSelectedItem(cd.ngheNghiep);
    }

    
    //timkiem
    public void find(){
        CongDan cd=new CongDan();
        cd.CMND=txtTimKiem.getText();
        for(int i=0;i<list.size();i++){
            if(list.get(i).CMND.equalsIgnoreCase(cd.CMND)){
                txtTen.setText(list.get(i).ten);
                cboNamSinh.setSelectedItem(list.get(i).namSinh);
                cboGioiTinh.setSelectedItem(list.get(i).gioiTinh);
                txtSoCMND.setText(list.get(i).CMND);
                txtQueQuan.setText(list.get(i).queQuan);
                txtChoOHienNay.setText(list.get(i).choOHienNay);
                cboNghe.setSelectedItem(list.get(i).ngheNghiep);
//                ImageIcon icon=new ImageIcon(cd.icon);
//        lblAnh.setIcon(icon);
            }
        }
    }
    
    //Record
int dem=0;
public void record(){
        for (int i = 0; i < list.size(); i++) {
            dem=tblBang.getSelectedRow();
            dem=dem+1;
            lblRecord.setText("Record: "+dem+" - "+list.size());
            
        }
        showDetail();
    }

    //Clock
    public void dongho() {
        Thread dh = new Thread() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Date now = new Date();
                        SimpleDateFormat formater = new SimpleDateFormat();
                        formater.applyPattern("hh:mm:ss aa");
                        String time = formater.format(now);
                        lblClock.setText(time);

                        Thread.sleep(1000);
                    } catch (Exception e) {
                        break;
                    }
                }
            }
        };
        dh.start();
    }
    //Trung CMND
   public void trungCMND(){
    for(int i=0;i<list.size();i++){
        if(list.get(i).CMND.equals(txtSoCMND.getText())){
            JOptionPane.showMessageDialog(this, "Bạn nhập số CMND bị trùng");
            txtSoCMND.setText("");
        }
    }
}
    private void btnTrangTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangTruocActionPerformed
        dem=0;
        tblBang.setRowSelectionInterval(dem, dem);
        record();
    }//GEN-LAST:event_btnTrangTruocActionPerformed

    private void cboNgheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNgheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNgheActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
          this.find();
          
          
            
            
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        txtTen.setText("");
        cboNamSinh.setSelectedItem("----");
        txtChoOHienNay.setText("");
        txtQueQuan.setText("");
        txtSoCMND.setText("");
        cboGioiTinh.setSelectedIndex(0);
        cboNghe.setSelectedIndex(0);
        lblAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/default.png")));

    }//GEN-LAST:event_btnMoiActionPerformed
//Sự kiện nút lưu
    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        //Kiểm tra lỗi
        //Kiểm tra số CMND
        Pattern pattern = Pattern.compile("^[0-9]*$");
        Matcher matcher = pattern.matcher(txtSoCMND.getText());
        if (!matcher.matches()) {
            JOptionPane.showMessageDialog(this, "CMND phải là số và không có khoảng trắng");
            txtSoCMND.setText("");
        }
        //Kiểm tra trùng số CMND
        trungCMND();
        //Kiểm tra tên
        Matcher math = pattern.matcher(txtTen.getText());
        if (math.matches()) {
            JOptionPane.showMessageDialog(this, "Họ tên bạn nhập không đúng");
            txtTen.setText("");
        }
        //Kiểm tra ô trống
        if (txtTen.getText().equals("") || cboNamSinh.getSelectedItem() == "----"
                || cboGioiTinh.getSelectedItem() == "---" || txtSoCMND.getText().equals("")
                || txtQueQuan.getText().equals("") || txtChoOHienNay.getText().equals("")
                || cboNghe.getSelectedItem() == "-------") {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ");

        }
        else {
            add();
            XFile.writeObject("d:/congdans.dat", list);
        }

    }//GEN-LAST:event_btnLuuActionPerformed
//Nút xóa
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.delete();
        this.fillTable();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void Picture(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Picture
        // TODO add your handling code here:
    }//GEN-LAST:event_Picture

    private void cboNamSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNamSinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNamSinhActionPerformed

    private void tblBangOnMouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangOnMouseClick
        this.showDetail();
       
    }//GEN-LAST:event_tblBangOnMouseClick
//Sự kiện nút mở
    private void btnMoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoActionPerformed
        list = (List<CongDan>) XFile.readObject("d:/congdans.dat");
        this.fillTable();
     

    }//GEN-LAST:event_btnMoActionPerformed

    private void btnTenTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTenTruocActionPerformed
        dem=tblBang.getSelectedRow();
        if (dem==0) {
            dem=list.size();
        }
        dem--;
        tblBang.setRowSelectionInterval(dem, dem);
        record();
    }//GEN-LAST:event_btnTenTruocActionPerformed

    private void btnTenSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTenSauActionPerformed
        dem=tblBang.getSelectedRow();
        dem++;
        if (dem==list.size())
            dem=0;
        tblBang.setRowSelectionInterval(dem, dem);
        record();
    }//GEN-LAST:event_btnTenSauActionPerformed

    private void btnTrangSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangSauActionPerformed
         dem=list.size()-1;
        tblBang.setRowSelectionInterval(dem, dem);
        record();
    }//GEN-LAST:event_btnTrangSauActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed
//Thêm ảnh
    String ImgPath=null;
    public ImageIcon ResizeImage(String imagePath,byte[] pic){
        ImageIcon myImage=null;
        if (imagePath!=null) {
            myImage=new ImageIcon(imagePath);
        }else {
            myImage=new ImageIcon(pic);
        }
        Image img=myImage.getImage();
        Image img2=img.getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img2);
        return image;
    }
    private void btnThemAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemAnhActionPerformed
        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.images", "jpg","png");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);
        if (result==JFileChooser.APPROVE_OPTION) {
            File selectedFile=file.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            lblAnh.setIcon(ResizeImage(path, null));
        } else{
            System.out.println("Không có file được chọn");
        }
    }//GEN-LAST:event_btnThemAnhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyCongDan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyCongDan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyCongDan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyCongDan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyCongDan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnMo;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnTenSau;
    private javax.swing.JButton btnTenTruoc;
    private javax.swing.JButton btnThemAnh;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTrangSau;
    private javax.swing.JButton btnTrangTruoc;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JComboBox<String> cboNamSinh;
    private javax.swing.JComboBox<String> cboNghe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblChoOHienNay;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblNamSinh;
    private javax.swing.JLabel lblNghe;
    private javax.swing.JLabel lblQueQuan;
    private javax.swing.JLabel lblRecord;
    private javax.swing.JLabel lblSoCMND;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txtChoOHienNay;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtSoCMND;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
